# Generated by Django 2.2.1 on 2020-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='polarity',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='subjectivity',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
