# Generated by Django 2.2.1 on 2020-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201017_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='polarity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='subjectivity',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
