# Generated by Django 2.2.1 on 2020-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201021_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('about_me', models.CharField(max_length=1000)),
                ('years_of_experience', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=1000)),
                ('specialisation', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=2000)),
                ('complex_cases_handled', models.CharField(max_length=2000)),
                ('availability', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('W', 'Worst'), ('G', 'Good'), ('B', 'Better- Slowly Recovering'), ('V', 'Vulnerable')], default='', max_length=300)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('severity', models.CharField(max_length=1000)),
                ('issues', models.CharField(max_length=1000)),
                ('date_admitted', models.DateField()),
                ('care_provided', models.CharField(choices=[('I', 'Intensive Care'), ('B', 'Behavioural Care'), ('P', 'Palliative Care'), ('O', 'Ordinary Care'), ('S', 'Special Care')], default='', max_length=1000)),
                ('care_needed', models.CharField(max_length=1000)),
                ('health_level', models.CharField(max_length=1000)),
                ('sex', models.CharField(max_length=1000)),
                ('cp', models.CharField(max_length=1000)),
                ('trestbps', models.CharField(max_length=1000)),
                ('chol', models.CharField(max_length=1000)),
                ('fbs', models.CharField(max_length=1000)),
                ('restecg', models.CharField(max_length=1000)),
                ('thalach', models.CharField(max_length=1000)),
                ('exang', models.CharField(max_length=1000)),
                ('oldpeak', models.CharField(max_length=1000)),
                ('slope', models.CharField(max_length=1000)),
                ('ca', models.CharField(max_length=1000)),
                ('thal', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('proof', models.CharField(max_length=200)),
                ('lisences_hold', models.CharField(max_length=200)),
                ('verfication_status', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('available_date', models.DateField()),
                ('services', models.CharField(max_length=1000)),
            ],
        ),
    ]
