# Generated by Django 2.2.1 on 2020-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201028_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='First_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='Second_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='criticality_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='e_y_s',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(default='University of WIndsor', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='few_words',
            field=models.CharField(default='Enthusiastic Gamer often iek to defeat others while playing multiplayer_game', max_length=2000),
        ),
        migrations.AddField(
            model_name='patient',
            name='n_y_c',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(default='Business Executive', max_length=200),
        ),
    ]
