# Generated by Django 2.2.1 on 2020-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20201029_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='id',
        ),
        migrations.AddField(
            model_name='nurse',
            name='First_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nurse',
            name='Second_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nurse',
            name='current_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nurse',
            name='few_words',
            field=models.CharField(default='Enthusiastic Gamer often iek to defeat others while playing multiplayer_game', max_length=2000),
        ),
        migrations.AddField(
            model_name='nurse',
            name='nationality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='operations_handled',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='nurse',
            name='patients_handled',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='nurse',
            name='pin_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='First_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Second_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='current_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='education',
            field=models.CharField(default='University of WIndsor', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email_address',
            field=models.EmailField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='few_words',
            field=models.CharField(default='Enthusiastic Gamer often iek to defeat others while playing multiplayer_game', max_length=2000),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nationality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='operations_handled',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='patients_helped',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='pin_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profession',
            field=models.CharField(default='Business Executive', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='vol_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteering_experience',
            field=models.IntegerField(default=10),
        ),
    ]
