# Generated by Django 2.2.1 on 2020-11-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20201029_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_habbits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Life_expectancy', models.IntegerField(default=10)),
                ('Alcohol_percentage', models.IntegerField(default=10)),
                ('expenditure_income', models.IntegerField(default=10)),
                ('STIs', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('BMI', models.IntegerField(default=10)),
                ('Polio', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('Total_expenditure', models.IntegerField(default=10)),
                ('Class', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('Adult_smoking', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('Physical_inactivity', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Patient')),
            ],
        ),
    ]
