# Generated by Django 2.2.1 on 2020-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_health_habbits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_habbits',
            name='Class',
            field=models.CharField(choices=[('A', 'Good'), ('B', 'Historical Complications'), ('C', 'Disaster due to unexpected situations')], default='', max_length=300),
        ),
    ]
